### ISSUE TITLE
Devicelocale.preferredLanguages returns only 1 language

### ISSUE THREAD

**Issue by ManojMM026** [magnatronus/flutter-devicelocale#10]
`Devicelocale.preferredLanguages ` returns only 1 language from phone i.e en_IN for Redmi phones. 

Also it will be great if we can have language name as well based on codes.

**Comment by magnatronus** [comment]
The plugin will only return what it finds when querying the phone. Does the phone your testing have more than 1 language installed or is en_IN the default ?

**Comment by ManojMM026** [comment]
![Screenshot_2020-01-15-16-14-34-633_com android settings](https://user-images.githubusercontent.com/2713390/72427734-67004a00-37b2-11ea-8673-7e3e32eacf7f.png)

These are the languages installed on my phone.

**Comment by ManojMM026** [comment]
what I have seen in your code is:  you are returning default locale if there is an exception getting list of languages.

**Comment by magnatronus** [comment]
@ManojMM026   Yes, so if for any reason the code cannot detect the list of languages it does at least return the default. Which is probably what is happening in this case.  What version of Android is on the device ?

**Comment by ManojMM026** [comment]
Its nougat 7.0

**Comment by magnatronus** [comment]
For some reason the call to 

Resources.getSystem().getConfiguration().getLocales().getAdjustedDefault()

must be causing an error which is why you only get 1 value. 
According to this Android API docs this call was introduced in API 24 (nougat) which is the version you have on the phone.

The issue is that maybe for some reason the nougat implementation on the phone is the cause. Apologies but not much I can do as I do not have a physical phone to test.

Can leave this open in case anyone else has the issue and a possible solution.

**Comment by ened** [comment]
The call should be using:

``` java
LocaleListCompat list = LocaleListCompat.getAdjustedDefault();
```

This is included in AndroidX. I will prepare a PR.
